### ISSUE TITLE
Please update software so we don't see this warning...

### ISSUE THREAD

**Issue by bigplayer-ai** [Gaulomatic/AirPodsSanity#16]
“AirPods Sanity.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by Gaulomatic** [comment]
Problem is the macOS Gatekeeper. I added instructions on how to avoid this error message. The message pops up because the app is not signed with a paid developer certificate.

Open the Terminal or iTerm and issue the following command:
`xattr -d com.apple.quarantine "/Applications/AirPods Sanity.app"`

https://github.com/Gaulomatic/AirPodsSanity/blob/main/README.md#installation
