### ISSUE TITLE
Why do we need to pick an output device as well?

### ISSUE THREAD

**Issue by BrajBliss** [Gaulomatic/AirPodsSanity#8]
Under [what it does](https://github.com/Gaulomatic/AirPodsSanity?tab=readme-ov-file#what-it-does):

> Select a default input device, **and mark one or more output device as "AirPods"**. 

I was using the original fixer app but found this so wanted to try. I connect multiple Earbuds like Realme, Nothing, etc. How is this output device setting helpful and what it does? Because in the fixer app, we only have to select the input device.

**Comment by Gaulomatic** [comment]
I found it somewhat annoying not being able to directly set the input device of my choice. This is mainly because I use one inout device only, so maintaining the previously set input device felt off. But I have to agree, it's a preference of my own line of thinking, so I will add the possibility to just use the input device that is currently active.

**Comment by Gaulomatic** [comment]
I just remembered that you don't have to select an input device. I built that in because I found it annoying that if the app is started after the AirPods connected, the app can't really do its stuff because in this edge case the AirPods are already the preferred input device. So unselect the device and the app will use the system input device. I will update the documentation to clarify this.
